### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by ulisesbocchio** [vdenotaris/spring-boot-security-saml-sample#27]
Hi, great app! I used your example little more than a year ago and since I created my own spring-boot SAML plugin. I'd like to get your input since you seem to be active in this topic.
https://github.com/ulisesbocchio/spring-boot-security-saml

**Comment by vdenotaris** [comment]
Hi.

Actually your application looks really intesting.
Since the configuration part is really verbose, it would be a nice upgrade for my project (and more in general for Spring SAML) follow your "short" annotation style format in order to tune the federation settings.

Let's Keep in touch.
Cheers, V.
