### ISSUE TITLE
Using TestRestTemplate

### ISSUE THREAD

**Issue by DenEwout** [vdenotaris/spring-boot-security-saml-sample#36]
Hello,

How would you go about writing test code with a TestRestTemplate instead of using mockMVC?

Kind Regards,

Ewout.

**Comment by vdenotaris** [comment]
Hi.
Due to the nature of this solution, as sample SP, the current test classes can be considered fine.
A web-based SAML authentication process (relying of WAYF) cannot be automatically tested, thus I cannot see in this right moment a valid reason to change the test classes.

However, any suggestion or contribution for improvement is well accepted.

Cheers, V.
